In [ ]:
import numpy as np
import torch as th

data = np.load('./data_for_lora/new_joints/demo_cr7_2.npy', allow_pickle=True)
print(data.shape)

(90, 22, 3)
[[ 5.55671230e-02  8.98453593e-01  2.36849282e-02]
 [ 5.72341457e-02  8.99195254e-01  2.32060812e-02]
 [ 5.95407747e-02  9.00675416e-01  2.16578804e-02]
 [ 6.20041788e-02  9.02562618e-01  2.36053690e-02]
 [ 6.45536631e-02  9.05310512e-01  2.65676472e-02]
 [ 6.34807646e-02  9.02413607e-01  1.66903548e-02]
 [ 6.49462640e-02  9.02395070e-01  1.22863054e-02]
 [ 6.41368926e-02  9.01124775e-01  2.29461677e-03]
 [ 6.28796518e-02  9.00528669e-01 -3.60845169e-03]
 [ 6.39488250e-02  8.99728656e-01 -1.76117150e-03]
 [ 6.36950433e-02  8.98704410e-01 -1.01522217e-03]
 [ 6.37526065e-02  8.99576008e-01  5.18024620e-03]
 [ 6.29905760e-02  8.99155378e-01  5.22516947e-03]
 [ 6.16536736e-02  8.98116052e-01  3.77559476e-03]
 [ 6.08043782e-02  8.98255229e-01 -1.93608669e-03]
 [ 6.05309829e-02  8.98498714e-01  6.19997038e-04]
 [ 5.60367703e-02  8.94338965e-01  3.13554332e-03]
 [ 5.11287823e-02  8.91804278e-01  1.19696846e-02]
 [ 4.64123115e-02  8.88807893e-01  1.21059315e-02]
 [ 4.40916829e-02  